### ISSUE TITLE
characters are not generated uniformly

### ISSUE THREAD

**Issue by mbican** [klughammer/node-randomstring#15]
numbers 0-7 are generated more often then other characters. Because the number of characters is 62. The random number from generator is 0-255. 256 is not multiple of 62.

You should replace
```
var index = bf.readUInt8(i) % chars.length;
```

with something like this:
```
while((random = bf.readUInt8(i++))>=248); // 248 = 4*62
index = random % 62;
```
to throw away the nonuniform remainder

**Comment by eliaskg** [comment]
I would totally merge this if you had a working fork 😉

**Comment by dchest** [comment]
@mbican could you please review #18.

**Comment by weisjohn** [comment]
:+1:

**Comment by eliaskg** [comment]
I tested this function wise and it works. Could anyone check whether characters now are really generated uniformly?

**Comment by dchest** [comment]
@eliaskg there's a test for uniformness included:

https://github.com/dchest/node-randomstring/commit/15ce2fd0841f46141cb2a3c7bf333e3ab064c416#diff-910eb6f57886ca16c136101fb1699231R79

If you want to see/graph the distribution, insert a few `console.log`'s there.
