### ISSUE TITLE
Option for case-insensitive char sets

### ISSUE THREAD

**Issue by Dortamur** [klughammer/node-randomstring#17]
Hi! Would it be possible to have some short-hand charset options - or a separate option - for generating all upper or all lower random strings?

Ideally, my current use-case I want 0-9 plus A-Z (but not  a-z).

**Comment by wolfy1339** [comment]
:+1:

**Comment by eliaskg** [comment]
Integrated in cef6a9a91f80fe17e984be973775ed9054d0d6d1
