### ISSUE TITLE
Getting lots of duplicates

### ISSUE THREAD

**Issue by petestreet** [klughammer/node-randomstring#22]
If I generate a number of random strings in close enough proximity to each other, they're all turning out the same.  After reading through your code, this seems like an issue inherent to `crypto`.  Any ideas on how to, e.g., seed the `crypto.randombytes` function with a `Date.now` timestamp?

**Comment by petestreet** [comment]
My specific use case is generating a random string that's saved along with a database document, so that it can be used in an "unlisted" shareable link.  Obviously that won't work if there's more than one document that will match that query.

**Comment by Dev43** [comment]
Why don't you simply use UID's? They are quasi-guaranteed to not have collisions. https://en.wikipedia.org/wiki/Unique_identifier

**Comment by eliaskg** [comment]
Thank you! Should be fixed via the latest version.
