### ISSUE TITLE
Support special characters?

### ISSUE THREAD

**Issue by Norfeldt** [klughammer/node-randomstring#30]
Would it be hard to add special characters like `!@#$%^` to the charset?

#FeatureRequest

**Comment by banothurameshnaik** [comment]
@Norfeldt 

Its not hard too :)

We can achieve your requirement by two approaches

1. Using existing charset

Here, we can get random string along with special characters by using `custom` type

**Example:**
```javascript

var randomstring = require("randomstring");

randomstring.generate({
  length: 10
  charset: '!@#$%^'
});

// >> "$!#$%^##@!"

```

2. Implementing new charset type in lib

By implementing another charset type in the lib with name of `specialchars` and its required chars 

Here you may require to define what type of chars you want to define
like only special chars or combination of special chars with any other types

**Note:** By assuming above implementation completed with type of `specialchars`

**Example:**
```javascript

var randomstring = require("randomstring");

randomstring.generate({
  length: 10
  charset: 'specialchars'
});

// >> "$!#$%^##@!"

```
I hope this helps you!

I am new to open source contribution,
If 2nd approach is accepted by team and you, I can contribute by implementing it.

Let me know you thoughts!

Thanks

**Comment by eliaskg** [comment]
Thanks @banothurameshnaik 

Closing this.
