### ISSUE TITLE
Random String with Prefix  

### ISSUE THREAD

**Issue by longmup** [klughammer/node-randomstring#31]
Is there a solution when using a random string that has a prefix for the generated string?
For example in case I want to generate 16 random characters but they all start with "AR", is there any solution for me?
Thank you!

**Comment by pavlikm** [comment]
you can make it in cycle:
```
let strings = [];
let prefix = "AR";
for(let i=0; i<16; i++){
   strings.push(prefix + randomstring.generate());
}
```

**Comment by eliaskg** [comment]
Thank you @pavlikm, that's exactly how I would suggest to get a prefix as it is quite simple.

Closing this.
