### ISSUE TITLE
Fails to generate strings in Electron

### ISSUE THREAD

**Issue by slashinfty** [klughammer/node-randomstring#34]
Unsure if it is due to it being Electron or running webpack-dev-server, but the catch block here runs indefinitely:
```js
function safeRandomBytes(length) {
  while (true) {
    try {
      return randomBytes(length);
    } catch(e) {
      continue;
    }
  }
}
```
The fact that randombytes operates differently in Node and in the browser seems like it could be the underlying cause.

**Comment by muhammadsumon** [comment]
Same! I can't use it in React Js.
