### ISSUE TITLE
Use crypto.randomBytes

### ISSUE THREAD

**Issue by luto** [klughammer/node-randomstring#4]
```js
return require('crypto').randomBytes(length).toString('hex');
```

**Comment by yetanotherusernamebecausegithubisbugged** [comment]
-1
.toString('hex') reduces result string alphabet to 'abcdef0123456789'

**Comment by luto** [comment]
@yetanotherusernamebecausegithubisbugged the alphabet does not matter because it is still 10 bytes worth of bits. They just need a little bit more space, but oh well..
Math.random is not in any way usable for crypto.

**Comment by yetanotherusernamebecausegithubisbugged** [comment]
@luto I was needed a password generator with a customizable alphabet that's why I was concerned about those things. But you're right about the rest so it's just an example you provided is a bit irrelevant to my specific needs.

**Comment by eliaskg** [comment]
What's the advantage to use ``crypto``over the existing method?

**Comment by luto** [comment]
The "random" numbers of `math.random()` aren't really usable for anything other than rolling dice in a game. Since an array of random bytes is often used as salt, token or other, they need to at least pretend to be cryptographically secure, which the `crypto` module provides.

**Comment by shackbarth** [comment]
+1 IMO it's very dangerous that the number one google result for "node random string" is for a module that's not cryptographically secure, and that you have to go digging in the source code to see that under the hood it's just `Math.random()`. There should at least be a prominent warning in the readme.

**Comment by micromaomao** [comment]
Pull request #14

**Comment by eliaskg** [comment]
Merged. Thanks!
